image: python:3.10-slim

stages:
  - build

build:
  stage: build

  rules:
    - if: $CI_COMMIT_TAG

  variables:
    TWINE_USERNAME: gitlab-ci-token
    TWINE_PASSWORD: $CI_JOB_TOKEN
    PIP_REPO: $CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/pypi

  script:
    - pip install build
    - pip install twine
    - python -m build
    - python -m twine upload --repository-url $PIP_REPO dist/*
